name: task-manager

networks:
  shared-network:
    external: true

services:
  spring-api:
    build:
      context: ./apps/task-manager
      dockerfile: Dockerfile
    container_name: spring_api
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - shared-network

  react-client:
    build:
      context: .
      dockerfile: ./apps/task-manager-client/Dockerfile
    container_name: react_client
    restart: always
    env_file:
      - ./apps/task-manager-client/.env.localhost
    ports:
      - "3000:3000"
    networks:
      - shared-network

  angular-backoffice:
    build:
      context: .
      dockerfile: ./apps/task-manager-backoffice/Dockerfile
    container_name: angular_backoffice
    restart: always
    ports:
      - "4200:4200"
    networks:
      - shared-network
