spring.datasource.url=jdbc:postgresql://ep-bitter-poetry-zaxorzab-pooler.c-2.eu-west-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_jRBr5NuJ3gYe&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jRBr5NuJ3gYe