/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all users
         * @description Retrieves a paginated list of users filtered by optional query criteria. Requires administrator privileges.
         */
        get: operations["getAll"];
        put?: never;
        /**
         * Create a user
         * @description Creates a new user in the system.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all tasks
         * @description Retrieves a paginated list of tasks filtered by optional query criteria.
         */
        get: operations["getAll_1"];
        put?: never;
        /**
         * Create a task
         * @description Creates a new task in the system.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User registration
         * @description Registers a new user account and returns initial JWT tokens.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT token
         * @description Generates a new access token using a valid refresh token.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticates user credentials and returns JWT access and refresh tokens.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by ID
         * @description Retrieves a single user by their unique identifier along with their total task count.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Permanently deletes a user account.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * Update user
         * @description Partially updates user profile information.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get task by ID
         * @description Retrieves a single task by its unique identifier along with owner details.
         */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        /**
         * Delete task
         * @description Permanently deletes a task.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * Update task
         * @description Partially updates task title or description.
         */
        patch: operations["update_1"];
        trace?: never;
    };
    "/tasks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Start task
         * @description Transitions task status to IN_PROGRESS.
         */
        patch: operations["start"];
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Complete task
         * @description Transitions task status to COMPLETED.
         */
        patch: operations["complete"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user profile
         * @description Retrieves the identity and profile information of the currently authenticated user based on the security context.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body required to register a new user in the system */
        UserCreateRequestDTO: {
            /**
             * @description First name of the user
             * @example John
             */
            name: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * Format: email
             * @description Unique email address for the user account
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Account password. Must meet length constraints
             * @example P@ssw0rd123!
             */
            password: string;
        };
        /** @description User response DTO including the calculated number of assigned tasks */
        UserWithTaskCountResponseDTO: {
            /**
             * Format: uuid
             * @description Unique identifier of the user
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            id?: string;
            /**
             * @description First name of the user
             * @example John
             */
            name?: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * @description Email address of the user
             * @example john.doe@example.com
             */
            email?: string;
            /**
             * Format: int64
             * @description Total count of tasks assigned to this user
             * @example 5
             */
            countTasks?: number;
            /**
             * Format: date-time
             * @description Timestamp when the user account was created
             * @example 2026-01-01T00:00:00Z
             */
            createdAt?: string;
        };
        /** @description Standardized error response returned when an API request fails */
        ErrorResponseDTO: {
            /**
             * Format: date-time
             * @description UTC timestamp when the error occurred
             * @example 2026-08-07T14:32:15Z
             */
            timestamp?: string;
            /**
             * Format: int32
             * @description HTTP status code integer value
             * @example 400
             */
            status?: number;
            /**
             * @description HTTP status phrase / category
             * @example Bad Request
             */
            error?: string;
            /**
             * @description Human-readable summary message describing the error
             * @example The request contains validation errors.
             */
            message?: string;
            /** @description Detailed list of field-level validation errors, if applicable */
            errors?: components["schemas"]["FieldErrorDTO"][];
        };
        /** @description Details of a specific field-level validation error */
        FieldErrorDTO: {
            /**
             * @description Name of the field or path variable that failed validation
             * @example email
             */
            field?: string;
            /**
             * @description The rejected value sent by the client, if available
             * @example invalid-email-format
             */
            value?: unknown;
            /**
             * @description User-friendly validation error message explaining the failure constraint
             * @example Email has to be valid
             */
            message?: string;
        };
        /** @description Request body required to create a new task */
        TaskCreateRequestDTO: {
            /**
             * Format: uuid
             * @description Unique identifier of the user to assign the task to
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            userId: string;
            /**
             * @description Title of the task
             * @example Implement OAuth2 login
             */
            title: string;
            /**
             * @description Detailed description of the task requirements
             * @example Add support for Google and GitHub OAuth2 authentication providers.
             */
            description: string;
        };
        /** @description Embedded user information nested inside task response DTOs */
        TaskUserResponseDTO: {
            /**
             * Format: uuid
             * @description Unique identifier of the user
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            id?: string;
            /**
             * @description First name of the user
             * @example John
             */
            name?: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * @description Email address of the user
             * @example john.doe@example.com
             */
            email?: string;
        };
        /** @description Composite task response containing task details and embedded owner user information */
        TaskWithUserResponseDTO: {
            /**
             * Format: uuid
             * @description Unique identifier of the task
             * @example 987e6543-e21b-12d3-a456-426655440000
             */
            id?: string;
            /**
             * @description Title of the task
             * @example Implement OAuth2 login
             */
            title?: string;
            /**
             * @description Detailed description of the task
             * @example Add support for Google and GitHub OAuth2 providers.
             */
            description?: string;
            /**
             * @description Current lifecycle status of the task
             * @example PENDING
             * @enum {string}
             */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED";
            /** @description Embedded user information of the task owner */
            user?: components["schemas"]["TaskUserResponseDTO"];
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-01-01T00:00:00Z
             */
            createdAt?: string;
        };
        /** @description Request body required for registering a new user account */
        AuthRegisterRequestDTO: {
            /**
             * @description First name of the user
             * @example John
             */
            name: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * Format: email
             * @description Unique email address for the account
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Password for the account
             * @example P@ssw0rd123!
             */
            password: string;
        };
        /** @description Response body returned upon successful authentication or token refresh */
        AuthResponseDTO: {
            /**
             * @description JWT Bearer access token for authenticating protected API requests
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token?: string;
            /**
             * @description JWT refresh token for obtaining new access tokens
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token?: string;
            /**
             * Format: int64
             * @description Access token lifetime duration in seconds
             * @example 3600
             */
            expires_in?: number;
        };
        /** @description Request body required for refreshing JWT access tokens */
        AuthRefreshRequestDTO: {
            /**
             * @description Valid JWT refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
        };
        /** @description Request body required for user login authentication */
        AuthLoginRequestDTO: {
            /**
             * Format: email
             * @description Registered email address of the user
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description User account password
             * @example P@ssw0rd123!
             */
            password: string;
        };
        /** @description Request body for updating user profile information. All fields are optional. */
        UserUpdateRequestDTO: {
            /**
             * @description Updated first name of the user
             * @example John
             */
            name?: string;
            /**
             * @description Updated last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * Format: email
             * @description Updated email address for the user account
             * @example john.updated@example.com
             */
            email?: string;
        };
        /** @description Request body for partially updating a task. At least one field must be provided. */
        TaskUpdateRequestDTO: {
            /**
             * @description Updated title for the task
             * @example Updated OAuth2 Login
             */
            title?: string;
            /**
             * @description Updated description of the task
             * @example Updated details regarding OAuth2 implementation.
             */
            description?: string;
        };
        /** @description Query parameter filters for searching and paginating users */
        UserFiltersDTO: {
            /**
             * @description Search keyword matching first name or last name
             * @example John
             */
            search?: string;
            /**
             * Format: uuid
             * @description User unique identifier constraint
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            userId?: string;
        };
        PageUserWithTaskCountResponseDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["UserWithTaskCountResponseDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        /** @description Authenticated user profile response payload */
        UserMeResponseDTO: {
            /**
             * Format: uuid
             * @description Unique identifier of the authenticated user
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            id?: string;
            /**
             * @description First name of the user
             * @example John
             */
            name?: string;
            /**
             * @description Last name of the user
             * @example Doe
             */
            lastname?: string;
            /**
             * @description Registered email address of the user
             * @example john.doe@example.com
             */
            email?: string;
        };
        /** @description Query parameter filters for querying and paginating tasks */
        TaskFiltersDTO: {
            /**
             * Format: uuid
             * @description Filter tasks by assigned user ID
             * @example 123e4567-e89b-12d3-a456-426655440000
             */
            userId?: string;
            /**
             * @description Search text pattern matching task title or description
             * @example OAuth2
             */
            search?: string;
            /**
             * @description Filter tasks by lifecycle status
             * @example PENDING
             * @enum {string}
             */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED";
        };
        PageTaskWithUserResponseDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["TaskWithUserResponseDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAll: {
        parameters: {
            query: {
                page?: number;
                limit?: number;
                filters: components["schemas"]["UserFiltersDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users retrieved successfully as a paginated collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageUserWithTaskCountResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequestDTO"];
            };
        };
        responses: {
            /** @description User created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithTaskCountResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query: {
                page?: number;
                limit?: number;
                filters: components["schemas"]["TaskFiltersDTO"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks retrieved successfully as a paginated collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTaskWithUserResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequestDTO"];
            };
        };
        responses: {
            /** @description Task created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskWithUserResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRegisterRequestDTO"];
            };
        };
        responses: {
            /** @description User registered and authenticated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequestDTO"];
            };
        };
        responses: {
            /** @description Token refreshed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequestDTO"];
            };
        };
        responses: {
            /** @description Authenticated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithTaskCountResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description User updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithTaskCountResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskWithUserResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdateRequestDTO"];
            };
        };
        responses: {
            /** @description Task updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskWithUserResponseDTO"];
                };
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task started successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task completed successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request is invalid or contains validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description You do not have permission to perform this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description The requested resource could not be found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponseDTO"];
                };
            };
            /** @description Authentication is required to access this resource. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
            /** @description An unexpected error occurred while processing the request. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDTO"];
                };
            };
        };
    };
}
